### ISSUE TITLE
feat: populate site with complete dataset

### ISSUE THREAD

**Issue by shlomomdahan** [jenkins-infra/stats.jenkins.io#68]
- https://github.com/shlomomdahan/stats2.jenkins.io/issues/8

Given the recent PR #67, we now have the data necessary to fully populate the site. 

I will address each page of the site in a separate PR to keep things neat. 
```[tasklist]
### Tasks
- [ ] https://github.com/jenkins-infra/stats.jenkins.io/pull/70
- [ ] https://github.com/jenkins-infra/stats.jenkins.io/pull/76
- [ ] https://github.com/jenkins-infra/stats.jenkins.io/pull/77
```

**Comment by shlomomdahan** [comment]
This issue can be closed as 3/3 related PRs have been merged.
